### ISSUE TITLE
日本語フォント

### ISSUE THREAD

**Issue by oppara** [oppara/diary#1]
```css
@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap");

body {
  font-family: "Noto Sans JP", sans-serif;
}
```
